### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#268]
I have not reviewed most recent changes yet, but somebody else downloaded the 1.1.6.3.5 branch and reported the following.

>Warning: Missing argument 5 for WC_Gateway_PayPal_Express_AngellEYE::add_line_item(), called in /usr/www/users/uni/dev-bbt.tep.2015/wp-content/plugins/paypal-woocommerce-1.1.6.3.5/classes/wc-gateway-paypal-express-angelleye.php on line 2685 and defined in /usr/www/users/uni/dev-bbt.tep.2015/wp-content/plugins/paypal-woocommerce-1.1.6.3.5/classes/wc-gateway-paypal-express-angelleye.php on line 2648

**Comment by angelleye** [comment]
I'm able to confirm that I see the same error in my PHP error log after running test orders with the latest update on 1.1.6.3.5.

>[14-Aug-2015 03:45:48 UTC] PHP Warning:  Missing argument 5 for WC_Gateway_PayPal_Express_AngellEYE::add_line_item(), called in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 2680 and defined in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 2643

**Comment by angelleye** [comment]
I am also seeing another error in here...

>[14-Aug-2015 03:46:16 UTC] PHP Notice:  Undefined variable: productid in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 2654

**Comment by angelleye** [comment]
And another I'm seeing quite a bit of in my logs after running test orders...

>[14-Aug-2015 03:46:28 UTC] PHP Notice:  Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-includes/taxonomy.php on line 4124

**Comment by nishitlangaliya** [comment]
Done, Pushed to 'Issue-268' branch and also merged to 1.1.6.3.5 branch .

<pre>Warning: Missing argument 5 for WC_Gateway_PayPal_Express_AngellEYE::add_line_item(), called in /usr/www/users/uni/dev-bbt.tep.2015/wp-content/plugins/paypal-woocommerce-1.1.6.3.5/classes/wc-gateway-paypal-express-angelleye.php on line 2685 and defined in /usr/www/users/uni/dev-bbt.tep.2015/wp-content/plugins/paypal-woocommerce-1.1.6.3.5/classes/wc-gateway-paypal-express-angelleye.php on line 2648</pre>

[Done, was able to reproduce and sorted]

<pre>[14-Aug-2015 03:45:48 UTC] PHP Warning: Missing argument 5 for WC_Gateway_PayPal_Express_AngellEYE::add_line_item(), called in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 2680 and defined in /home/angelley/sandbox_woocommerce/wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php on line 2643</pre>

[Done, was able to reproduce this case and sorted]


<pre>[14-Aug-2015 03:46:28 UTC] PHP Notice: Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-includes/taxonomy.php on line 4124</pre>

[Right now, I was not able to reproduce this case . today while testing once i get this will sort it out and let you know for the same]

**Comment by angelleye** [comment]
I am still seeing this error when I go through checkouts.

>[18-Aug-2015 05:57:30 UTC] PHP Notice:  Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-includes/taxonomy.php on line 4128

It's only showing up in the PHP log file.  It doesn't cause a problem with the checkout itself, so it must be happening with one of the AJAX calls at some point..??

**Comment by angelleye** [comment]
I just did a test using the WooCommerce checkout page and paying with Express Checkout.  The PHP error log did not register anything until I made it all the way to the final receipt page.  

Everything looked good in the browser, and the order did work, but the PHP log now shows:

>[18-Aug-2015 06:12:07 UTC] PHP Notice:  get_formatted_legacy is <strong>deprecated</strong> since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /home/angelley/sandbox_woocommerce/wp-includes/functions.php on line 3391
[18-Aug-2015 06:12:16 UTC] PHP Notice:  Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-includes/taxonomy.php on line 4124
[18-Aug-2015 06:12:16 UTC] PHP Notice:  Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-includes/taxonomy.php on line 4128

**Comment by nishitlangaliya** [comment]
Hi Andrew,

-- > [18-Aug-2015 06:12:07 UTC] PHP Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /home/angelley/sandbox_woocommerce/wp-includes/functions.php on line 3391]

[Done, I was able to reproduce below case and and sorted out the get_formatted_legacy issues for all three payment getway. ]

--> [18-Aug-2015 06:12:16 UTC] PHP Notice: Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-includes/taxonomy.php on line 4124]

[ For this case I was still not able to reproduce case. I had created all settings as per woo.angelleye.com for woocommerce and created produce with same variations as per woo.angelleye.com but did not get an error. Would you please provide me one small video of this case so that if i miss any settings or something in my local server . I can reproduce it and sort it out.]

->  In this Issue I have also handled  the ' scroll to top' when we do not select terms and condtions. as we discussed in skype.]

Latest code pushed to 'Issue-268A' branch and merged to 1.1.6.3.5 branch for a review.

**Comment by nishitlangaliya** [comment]
While testing $selected_shipping_method_id variable undefined error was came, now it's handled and latest code merged to 1.1.6.3.5 branch for a review.
